[package]
name = "rust-flashcards"
version = "0.1.0"
authors = ["Krah <fehuschluk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.21.0", features = ["bundled"] }
iced = "0.1"